In [3]:
from __future__ import print_function
import torch

# 1. Tensor

## 1-1. Tensors

초기화되지 않은 5x3 행렬을 생성합니다.

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7418e+28, 7.3881e+31, 4.5277e+21],
        [1.9284e+31, 1.1434e+27, 7.0292e+28],
        [1.1022e+24, 1.8179e+31, 2.9967e+32],
        [1.1836e+22, 4.7424e+30, 2.0022e-19],
        [6.7422e+22, 6.1083e-04, 4.6165e+24]])


무작위로 초기화 된 5x3 행렬을 생성합니다.

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1564, 0.8521, 0.3317],
        [0.9629, 0.5540, 0.2182],
        [0.0425, 0.8843, 0.6447],
        [0.2421, 0.9856, 0.1241],
        [0.2637, 0.3533, 0.3221]])


0으로 채워치고 data type이 long인 5x3 행렬을 생성합니다.

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


python의 기본 자료구조인 List 혹은 Tuple을 사용해서 직접 텐서를 만들 수 있습니다.

In [11]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


size() 메서드는 행렬의 크기를 반환합니다.

In [12]:
print(x.size())

torch.Size([2])


## 1-2. Operation
행렬 연산을 위한 메서드는 여러 가지가 있습니다.

\+ 연산자로 행렬을 더할 수 있습니다.

In [14]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1815, 1.2133, 0.7711],
        [0.6833, 0.3907, 0.3784],
        [1.6781, 0.9620, 0.6559],
        [1.5542, 1.3535, 0.1601],
        [0.9037, 1.4912, 0.7258]])


torch.add 메서드 또한 같은 연산을 수행합니다.

In [17]:
print(torch.add(x, y))

tensor([[1.1815, 1.2133, 0.7711],
        [0.6833, 0.3907, 0.3784],
        [1.6781, 0.9620, 0.6559],
        [1.5542, 1.3535, 0.1601],
        [0.9037, 1.4912, 0.7258]])


아래와 같은 방식도 가능합니다.

In [21]:
print(x.add(y))

tensor([[1.1815, 1.2133, 0.7711],
        [0.6833, 0.3907, 0.3784],
        [1.6781, 0.9620, 0.6559],
        [1.5542, 1.3535, 0.1601],
        [0.9037, 1.4912, 0.7258]])


out 매개변수를 이용하여 출력값을 바로 대입할 수 있습니다.

In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1815, 1.2133, 0.7711],
        [0.6833, 0.3907, 0.3784],
        [1.6781, 0.9620, 0.6559],
        [1.5542, 1.3535, 0.1601],
        [0.9037, 1.4912, 0.7258]])


{Tensor 변수}.add_({Tensor 변수})를 사용하면 메서드를 호출한 텐서에 값이 바로 적용됩니다.

In [23]:
y.add_(x)
print(y)

tensor([[1.1815, 1.2133, 0.7711],
        [0.6833, 0.3907, 0.3784],
        [1.6781, 0.9620, 0.6559],
        [1.5542, 1.3535, 0.1601],
        [0.9037, 1.4912, 0.7258]])


Tensor는 Numpy처럼 인덱싱, 슬라이싱이 가능합니다.

In [25]:
print(x[:, 1])

tensor([0.3274, 0.3534, 0.9186, 0.4210, 0.8238])


Tensor의 크기나 모양을 변경하려면 torch.view 메서드를 사용할 수 있습니다.

In [27]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에 수에 따라 자동으로 맞춰지는 특수한 값입니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


하나의 값을 가진 텐서라면, item() 메서드를 사용하여 파이썬 숫자 자료형으로 반환할 수 있습니다.

In [28]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0115])
1.0115443468093872


## 1-3. Converting a Torch Tensor to a NumPy Array

In [29]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


numpy() 메서드를 사용하여 Tensor를 Numpy Array로 변환할 수 있습니다.

In [33]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [34]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 1-4. Converting NumPy Array to Torch Tensor

In [35]:
import numpy as np

torch.from_numpy() 메서드를 사용하면 Numpy Array를 Tensor로 변환할 수 있습니다.

In [37]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 1-5. CUDA Tensor

Tensor는 to() 메서드를 사용하여 모든 환경에 적응시킬 수 있습니다.

아래 코드는 GPU가 사용 가능하다면 GPU로 연산, GPU가 사용이 불가능하다면 CPU 로 연산하기 위한 코드입니다.

In [39]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [40]:
y = torch.ones_like(x, device=device)
x = x.to(device)
print(y, x)

tensor([1.], device='cuda:0') tensor([1.0115], device='cuda:0')
